2025-05-03 16:05:05 - INFO - Checking for leader...
2025-05-03 16:05:05 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:05:10 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:05:10 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:05:35 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:05:35 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "kenny"

2025-05-03 16:05:35 - INFO - [MAIN] kenny connected.
2025-05-03 16:05:37 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/kennygu/school/s25/cs262/cs2620_poker/server_lobby.py", line 525, in handle_requests
    for req in request_iterator:
               ^^^^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ~~~~~~~~~~^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:05:37 - INFO - [MAIN] kenny disconnected.
2025-05-03 16:05:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:05:48 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "kenny"

2025-05-03 16:05:48 - INFO - [MAIN] kenny connected.
2025-05-03 16:05:49 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/kennygu/school/s25/cs262/cs2620_poker/server_lobby.py", line 525, in handle_requests
    for req in request_iterator:
               ^^^^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ~~~~~~~~~~^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:05:56 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/kennygu/school/s25/cs262/cs2620_poker/server_lobby.py", line 525, in handle_requests
    for req in request_iterator:
               ^^^^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ~~~~~~~~~~^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/kennygu/venvs/cs2620/lib/python3.13/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:05:56 - INFO - [MAIN] kenny disconnected.
2025-05-03 16:15:50 - INFO - Checking for leader...
2025-05-03 16:15:50 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:15:55 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 16:15:55 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:17:12 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:12 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:17:12 - INFO - [MAIN] nick connected.
2025-05-03 16:17:20 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:20 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:17:20 - INFO - [MAIN] nick2 connected.
2025-05-03 16:17:21 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:21 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:17:22 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:22 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:17:23 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:23 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:17:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:25 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:17:26 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:26 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:17:27 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:27 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:17:28 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:28 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:17:29 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:29 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:17:31 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 527, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:17:32 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 527, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:17:51 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:51 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:17:51 - INFO - [MAIN] nick connected.
2025-05-03 16:17:53 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:53 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:17:53 - INFO - [MAIN] nick2 connected.
2025-05-03 16:17:54 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:54 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:17:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:56 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:17:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:56 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:17:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:17:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:18:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:18:00 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:18:02 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 527, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:18:03 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 527, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:18:03 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 527, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:18:05 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:18:05.967966-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:18:05 - INFO - Checking for leader...
2025-05-03 16:45:09 - INFO - Checking for leader...
2025-05-03 16:45:09 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:45:14 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:45:14 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:47:37 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:47:37.671692-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:47:37 - INFO - Checking for leader...
2025-05-03 16:47:45 - INFO - Checking for leader...
2025-05-03 16:47:45 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:47:50 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:47:50.685835-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-05-03 16:47:50 - ERROR - Error connecting to 127.0.0.1:50001: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-05-03T16:47:50.686558-04:00"}"
>
2025-05-03 16:47:50 - INFO - Checking for leader...
2025-05-03 16:48:05 - INFO - Checking for leader...
2025-05-03 16:48:05 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:48:10 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:48:10 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:48:36 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:48:36.074631-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:48:36 - INFO - Checking for leader...
2025-05-03 16:48:55 - INFO - Checking for leader...
2025-05-03 16:48:55 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:49:00 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:49:00 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:49:11 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:49:11 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:49:11 - INFO - [MAIN] nick connected.
2025-05-03 16:49:32 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:49:32 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:49:32 - INFO - [MAIN] nick2 connected.
2025-05-03 16:49:33 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:49:33 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:49:36 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:49:36 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:49:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:49:39 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:49:40 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:49:52 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:50:20 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T16:50:20.646716-04:00"}"
>
2025-05-03 16:50:20 - INFO - Checking for leader...
2025-05-03 16:50:28 - INFO - Checking for leader...
2025-05-03 16:50:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:50:33 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 16:50:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:50:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:50:56 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:50:56 - INFO - [MAIN] nick2 connected.
2025-05-03 16:50:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:50:57 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:50:57 - INFO - [MAIN] nick connected.
2025-05-03 16:50:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:50:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:50:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:50:58 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:50:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:50:59 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:00 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:01 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:01 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:02 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:02 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:03 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:03 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:04 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:04 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:05 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:51:05 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 16:51:05 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:51:07 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:52:08 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:52:08.71897-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:52:08 - INFO - Checking for leader...
2025-05-03 16:52:14 - INFO - Checking for leader...
2025-05-03 16:52:14 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:52:19 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:52:19 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:52:34 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:52:34 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:52:34 - INFO - [MAIN] nick connected.
2025-05-03 16:52:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:52:40 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:52:40 - INFO - [MAIN] nick2 connected.
2025-05-03 16:52:41 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:52:41 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:52:42 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:52:42 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:52:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:52:44 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:53:23 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:53:23.590521-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:53:23 - INFO - Checking for leader...
2025-05-03 16:53:32 - INFO - Checking for leader...
2025-05-03 16:53:32 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:53:37 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 16:53:37 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:53:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:53:50 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:53:50 - INFO - [MAIN] nick connected.
2025-05-03 16:53:55 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:53:55 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:53:55 - INFO - [MAIN] nick2 connected.
2025-05-03 16:53:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:53:56 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:53:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:53:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:53:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:53:58 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:53:58 - ERROR - [MAIN] Error handling requests at line 498: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 601, in handle_requests
    game.play_next(req)
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 473, in play_next
    self.reset_for_round()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 305, in reset_for_round
    self.end()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 498, in end
    game_history=main_pb2.GameHistoryEntry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation

2025-05-03 16:53:58 - INFO - [MAIN] nick disconnected.
2025-05-03 16:54:02 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 543, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 16:54:02 - INFO - [MAIN] nick2 disconnected.
2025-05-03 16:54:40 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T16:54:40.630259-04:00"}"
>
2025-05-03 16:54:40 - INFO - Checking for leader...
2025-05-03 16:55:28 - INFO - Checking for leader...
2025-05-03 16:55:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:55:33 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 16:55:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:55:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:55:57 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:55:57 - INFO - [MAIN] nick connected.
2025-05-03 16:56:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:56:02 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:56:02 - INFO - [MAIN] nick2 connected.
2025-05-03 16:56:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:56:02 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:56:03 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:56:03 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:56:04 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:56:04 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:56:04 - ERROR - [MAIN] Error handling requests at line 494: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 599, in handle_requests
    game.play_next(req)
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 473, in play_next
    self.reset_for_round()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 305, in reset_for_round
    self.end()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 494, in end
    game_history=main_pb2.GameHistoryEntry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation

2025-05-03 16:56:04 - INFO - [MAIN] nick disconnected.
2025-05-03 16:57:11 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T16:57:11.4096-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 16:57:11 - INFO - Checking for leader...
2025-05-03 16:57:19 - INFO - Checking for leader...
2025-05-03 16:57:19 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:57:24 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 16:57:24 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:57:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:57:56 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:57:56 - INFO - [MAIN] nick connected.
2025-05-03 16:58:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:58:01 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:58:01 - INFO - [MAIN] nick2 connected.
2025-05-03 16:58:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:58:02 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:58:03 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:58:03 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:58:05 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:58:05 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:58:05 - ERROR - [MAIN] Error handling requests at line 494: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 599, in handle_requests
    game.play_next(req)
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 473, in play_next
    self.reset_for_round()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 305, in reset_for_round
    self.end()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 494, in end
    game_history=main_pb2.GameHistoryEntry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation

2025-05-03 16:58:05 - INFO - [MAIN] nick disconnected.
2025-05-03 16:59:08 - INFO - Checking for leader...
2025-05-03 16:59:08 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 16:59:13 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 16:59:13 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 16:59:29 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:59:29 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 16:59:29 - INFO - [MAIN] nick connected.
2025-05-03 16:59:34 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:59:34 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 16:59:34 - INFO - [MAIN] nick2 connected.
2025-05-03 16:59:35 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:59:35 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 16:59:36 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:59:36 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 16:59:41 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 16:59:41 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 16:59:41 - ERROR - [MAIN] Error handling requests at line 494: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 599, in handle_requests
    game.play_next(req)
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 473, in play_next
    self.reset_for_round()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 305, in reset_for_round
    self.end()
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 494, in end
    game_history=main_pb2.GameHistoryEntry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad argument type for built-in operation

2025-05-03 16:59:41 - INFO - [MAIN] nick disconnected.
2025-05-03 17:00:09 - INFO - Checking for leader...
2025-05-03 17:00:09 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:00:14 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:00:14 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:00:34 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:00:34 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:00:34 - INFO - [MAIN] nick2 connected.
2025-05-03 17:00:38 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:00:38 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:00:38 - INFO - [MAIN] nick connected.
2025-05-03 17:00:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:00:39 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:00:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:00:40 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:00:41 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:00:41 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:01:01 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:01:03 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:03:06 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:03:06.108425-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:03:06 - INFO - Checking for leader...
2025-05-03 17:03:12 - INFO - Checking for leader...
2025-05-03 17:03:12 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:03:17 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:03:17 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:03:33 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:03:33 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:03:33 - INFO - [MAIN] nick connected.
2025-05-03 17:03:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:03:39 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:03:39 - INFO - [MAIN] nick2 connected.
2025-05-03 17:03:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:03:40 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:03:41 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:03:41 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:03:42 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:03:42 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:04:17 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:04:17.83346-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:04:17 - INFO - Checking for leader...
2025-05-03 17:04:28 - INFO - Checking for leader...
2025-05-03 17:04:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:04:33 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:04:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:04:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:04:50 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:04:50 - INFO - [MAIN] nick connected.
2025-05-03 17:04:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:04:56 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:04:56 - INFO - [MAIN] nick2 connected.
2025-05-03 17:04:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:04:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:04:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:04:58 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:04:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:04:59 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:05:01 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:05:02 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:05:28 - INFO - Checking for leader...
2025-05-03 17:05:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:05:33 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:05:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:05:53 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:05:53 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:05:53 - INFO - [MAIN] nick2 connected.
2025-05-03 17:05:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:05:56 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:05:56 - INFO - [MAIN] nick connected.
2025-05-03 17:05:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:05:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:05:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:05:57 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:05:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:05:59 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:06:00 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:06:01 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:07:44 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:07:44.228819-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:07:44 - INFO - Checking for leader...
2025-05-03 17:07:51 - INFO - Checking for leader...
2025-05-03 17:07:51 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:07:56 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:07:56 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:08:09 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:08:09 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:08:09 - INFO - [MAIN] nick connected.
2025-05-03 17:08:16 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:08:16 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:08:16 - INFO - [MAIN] nick2 connected.
2025-05-03 17:08:17 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:08:17 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:08:18 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:08:18 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:08:20 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:08:20 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:08:21 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:08:23 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 541, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:09:12 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:09:12.008512-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:09:12 - INFO - Checking for leader...
2025-05-03 17:11:36 - INFO - Checking for leader...
2025-05-03 17:11:36 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:11:41 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:11:41 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:11:54 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:11:54 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:11:54 - INFO - [MAIN] nick connected.
2025-05-03 17:11:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:11:59 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:11:59 - INFO - [MAIN] nick2 connected.
2025-05-03 17:12:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:12:00 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:12:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:12:01 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:12:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:12:02 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:14:01 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:14:01.347522-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:14:01 - INFO - Checking for leader...
2025-05-03 17:14:14 - INFO - Checking for leader...
2025-05-03 17:14:14 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:14:19 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:14:19 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:15:20 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:20 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:15:20 - INFO - [MAIN] nick connected.
2025-05-03 17:15:24 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:24 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:15:24 - INFO - [MAIN] nick2 connected.
2025-05-03 17:15:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:25 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:15:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:25 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:15:27 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:27 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 17:15:27 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:27 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 17:15:28 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:15:28 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:16:01 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:16:01.544267-04:00"}"
>
2025-05-03 17:16:01 - INFO - Checking for leader...
2025-05-03 17:16:35 - INFO - Checking for leader...
2025-05-03 17:16:35 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:16:40 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:16:40 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:16:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:16:44 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:16:44 - INFO - [MAIN] nick connected.
2025-05-03 17:16:45 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:16:45 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:16:45 - INFO - [MAIN] nick2 connected.
2025-05-03 17:16:46 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:16:46 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:16:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:16:47 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:16:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:16:48 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:17:27 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:17:27.716893-04:00"}"
>
2025-05-03 17:17:27 - INFO - Checking for leader...
2025-05-03 17:17:37 - INFO - Checking for leader...
2025-05-03 17:17:37 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:17:42 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:17:42 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:17:54 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:17:54 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:17:54 - INFO - [MAIN] nick connected.
2025-05-03 17:17:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:17:58 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:17:58 - INFO - [MAIN] nick2 connected.
2025-05-03 17:17:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:17:59 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:18:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:18:00 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:18:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:18:01 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:18:02 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:18:03 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:18:27 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:18:27.210444-04:00"}"
>
2025-05-03 17:18:27 - INFO - Checking for leader...
2025-05-03 17:18:35 - INFO - Checking for leader...
2025-05-03 17:18:35 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:18:40 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:18:40 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:19:07 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:19:07 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:19:07 - INFO - [MAIN] nick connected.
2025-05-03 17:19:12 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:19:12 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:19:12 - INFO - [MAIN] nick2 connected.
2025-05-03 17:19:13 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:19:13 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:19:14 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:19:14 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:19:15 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:19:15 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:19:16 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:19:17 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:19:48 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:19:48.60054-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:19:48 - INFO - Checking for leader...
2025-05-03 17:20:05 - INFO - Checking for leader...
2025-05-03 17:20:05 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:20:10 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:20:10.865393-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-05-03 17:20:10 - ERROR - Error connecting to 127.0.0.1:50001: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:20:10.86601-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-05-03 17:20:10 - INFO - Checking for leader...
2025-05-03 17:26:28 - INFO - Checking for leader...
2025-05-03 17:26:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:26:33 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:26:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:26:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:26:44 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:26:44 - INFO - [MAIN] nick connected.
2025-05-03 17:26:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:26:48 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:26:48 - INFO - [MAIN] nick2 connected.
2025-05-03 17:26:49 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:26:49 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:26:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:26:50 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:26:52 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:26:52 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:26:53 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:26:54 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:27:21 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:27:21.578948-04:00"}"
>
2025-05-03 17:27:21 - INFO - Checking for leader...
2025-05-03 17:27:26 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:27:26 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:29:40 - INFO - Checking for leader...
2025-05-03 17:29:40 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:29:45 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:29:45 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:29:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:29:59 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:29:59 - INFO - [MAIN] nick connected.
2025-05-03 17:30:05 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:30:05 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:30:05 - INFO - [MAIN] nick2 connected.
2025-05-03 17:30:06 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:30:06 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:30:07 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:30:07 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:30:08 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:30:08 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:30:08 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:30:37 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:30:37.316791-04:00"}"
>
2025-05-03 17:30:37 - INFO - Checking for leader...
2025-05-03 17:31:37 - INFO - Checking for leader...
2025-05-03 17:31:37 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:31:42 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:31:42 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:31:55 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:31:55 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:31:55 - INFO - [MAIN] nick connected.
2025-05-03 17:32:02 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:32:02 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:32:02 - INFO - [MAIN] nick2 connected.
2025-05-03 17:32:04 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:32:04 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:32:05 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:32:05 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:32:13 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:32:13 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:32:14 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:32:15 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:33:09 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:33:09.923389-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:33:09 - INFO - Checking for leader...
2025-05-03 17:33:18 - INFO - Checking for leader...
2025-05-03 17:33:18 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:33:23 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:33:23 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:33:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:33:59 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:33:59 - INFO - [MAIN] nick2 connected.
2025-05-03 17:34:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:34:00 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:34:00 - INFO - [MAIN] nick connected.
2025-05-03 17:34:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:34:00 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:34:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:34:01 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:34:03 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:34:03 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:34:03 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:34:04 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:34:52 - INFO - Checking for leader...
2025-05-03 17:34:52 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:34:57 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:34:57 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:35:34 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:34 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 17:35:34 - INFO - [MAIN] nick connected.
2025-05-03 17:35:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:39 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 17:35:39 - INFO - [MAIN] nick2 connected.
2025-05-03 17:35:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:40 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 17:35:41 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:41 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 17:35:43 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:43 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 17:35:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 17:35:44 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 17:35:45 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:35:46 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 542, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 17:36:03 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T17:36:03.724923-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 17:36:03 - INFO - Checking for leader...
2025-05-03 17:53:03 - INFO - Checking for leader...
2025-05-03 17:53:03 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:53:08 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:53:08 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:55:38 - INFO - Checking for leader...
2025-05-03 17:55:38 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:55:43 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 17:55:43 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:56:43 - INFO - Checking for leader...
2025-05-03 17:56:43 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:56:48 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:56:48 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 17:58:45 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T17:58:45.052464-04:00"}"
>
2025-05-03 17:58:45 - INFO - Checking for leader...
2025-05-03 17:58:52 - INFO - Checking for leader...
2025-05-03 17:58:52 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 17:58:57 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 17:58:57 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:00:49 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:00:49.768101-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:00:49 - INFO - Checking for leader...
2025-05-03 18:00:54 - INFO - Checking for leader...
2025-05-03 18:00:54 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:00:59 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 18:00:59 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:01:54 - INFO - Checking for leader...
2025-05-03 18:01:54 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:01:59 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:01:59 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:02:39 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T18:02:39.103957-04:00"}"
>
2025-05-03 18:02:39 - INFO - Checking for leader...
2025-05-03 18:02:48 - INFO - Checking for leader...
2025-05-03 18:02:48 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:02:53 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:02:53 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:03:27 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:03:27.58196-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:03:27 - INFO - Checking for leader...
2025-05-03 18:03:35 - INFO - Checking for leader...
2025-05-03 18:03:35 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:03:40 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:03:40 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:04:32 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:04:32.408699-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:04:32 - INFO - Checking for leader...
2025-05-03 18:04:40 - INFO - Checking for leader...
2025-05-03 18:04:40 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:04:45 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:04:45 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:05:44 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:05:44.665347-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:05:44 - INFO - Checking for leader...
2025-05-03 18:06:04 - INFO - Checking for leader...
2025-05-03 18:06:04 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:06:09 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:06:09 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:08:06 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:08:06.953864-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:08:06 - INFO - Checking for leader...
2025-05-03 18:09:29 - INFO - Checking for leader...
2025-05-03 18:09:29 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:09:34 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:09:34 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:10:33 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T18:10:33.279249-04:00"}"
>
2025-05-03 18:10:33 - INFO - Checking for leader...
2025-05-03 18:14:38 - INFO - Checking for leader...
2025-05-03 18:14:38 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:14:43 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:14:43 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:15:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:15:25 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 18:15:25 - INFO - [MAIN] nick connected.
2025-05-03 18:15:26 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 547, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 18:15:26 - INFO - [MAIN] nick disconnected.
2025-05-03 18:21:13 - INFO - Checking for leader...
2025-05-03 18:21:13 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:21:18 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 18:21:18 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:21:32 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:32 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 18:21:32 - INFO - [MAIN] nick connected.
2025-05-03 18:21:36 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:36 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 18:21:36 - INFO - [MAIN] nick2 connected.
2025-05-03 18:21:38 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:38 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 18:21:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:39 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 18:21:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:39 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:40 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:44 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: RAISE
amount: 4

2025-05-03 18:21:46 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:46 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:47 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:47 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:48 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:48 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:49 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:49 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:51 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 18:21:51 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 18:21:52 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 547, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 18:21:55 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 547, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 18:40:18 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:40:18.769218-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:40:18 - INFO - Checking for leader...
2025-05-03 18:40:21 - INFO - Checking for leader...
2025-05-03 18:40:21 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:40:27 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:40:27 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:43:19 - INFO - Checking for leader...
2025-05-03 18:43:19 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:43:24 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 18:43:24 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:46:45 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T18:46:45.121649-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 18:46:45 - INFO - Checking for leader...
2025-05-03 18:47:05 - INFO - Checking for leader...
2025-05-03 18:47:05 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:47:10 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:47:10 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:48:23 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-03T18:48:23.017818-04:00"}"
>
2025-05-03 18:48:23 - INFO - Checking for leader...
2025-05-03 18:48:30 - INFO - Checking for leader...
2025-05-03 18:48:30 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:48:35 - INFO - Leader found: 127.0.0.1:50000
2025-05-03 18:48:35 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 18:51:02 - INFO - Checking for leader...
2025-05-03 18:51:02 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 18:51:07 - INFO - Leader found: 127.0.0.1:50001
2025-05-03 18:51:07 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 19:12:40 - INFO - Checking for leader...
2025-05-03 19:12:40 - INFO - [SETUP] Lobby server started on port 60000
2025-05-03 19:12:45 - INFO - Leader found: 127.0.0.1:50004
2025-05-03 19:12:45 - INFO - Info came from: 127.0.0.1:50000
2025-05-03 19:13:45 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:45 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-03 19:13:45 - INFO - [MAIN] nick connected.
2025-05-03 19:13:46 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:46 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-03 19:13:46 - INFO - [MAIN] nick2 connected.
2025-05-03 19:13:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:47 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-03 19:13:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:48 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-03 19:13:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:50 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:13:51 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:51 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:13:52 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:52 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:13:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:13:59 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 19:14:03 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:03 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:04 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:04 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:06 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:06 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:15 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:15 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: RAISE
amount: 44

2025-05-03 19:14:16 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:16 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:17 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:17 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:18 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:18 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:19 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:19 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:19 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:19 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:21 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:21 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-03 19:14:23 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:23 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 19:14:24 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:24 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 19:14:24 - INFO - [MAIN] Size of request: 80 bytes
2025-05-03 19:14:24 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-03 19:14:26 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 910, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 19:14:27 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 910, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-03 19:14:43 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-03T19:14:43.903778-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-03 19:14:43 - INFO - Checking for leader...
2025-05-04 00:50:06 - INFO - Checking for leader...
2025-05-04 00:50:06 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 00:50:11 - INFO - Leader found: 127.0.0.1:50001
2025-05-04 00:50:11 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 00:50:52 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:52 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-04 00:50:52 - INFO - [MAIN] nick connected.
2025-05-04 00:50:53 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:53 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-04 00:50:53 - INFO - [MAIN] nick2 connected.
2025-05-04 00:50:54 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:54 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-04 00:50:55 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:55 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-04 00:50:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:57 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:50:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:58 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:50:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:50:58 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:52:22 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-04T00:52:22.878571-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-04 00:52:22 - INFO - Checking for leader...
2025-05-04 00:52:27 - INFO - Leader found: 127.0.0.1:50004
2025-05-04 00:52:27 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 00:52:38 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:38 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 00:52:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:39 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:52:39 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:39 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:52:40 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:40 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:52:43 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:43 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: RAISE
amount: 54

2025-05-04 00:52:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:44 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 00:52:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:44 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 00:52:45 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:45 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 00:52:46 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:46 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 00:52:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 00:52:47 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 00:52:50 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 910, in handle_requests
    new_player = Player(req.username, client_queue)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 00:53:58 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-04T00:53:58.74036-04:00"}"
>
2025-05-04 00:53:58 - INFO - Checking for leader...
2025-05-04 14:05:16 - INFO - Checking for leader...
2025-05-04 14:05:16 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 14:05:21 - INFO - Leader found: 127.0.0.1:50003
2025-05-04 14:05:21 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 14:05:35 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:35 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-04 14:05:35 - INFO - [MAIN] nick connected.
2025-05-04 14:05:42 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:42 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick2"

2025-05-04 14:05:42 - INFO - [MAIN] nick2 connected.
2025-05-04 14:05:43 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:43 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-04 14:05:44 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:44 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick2"
vote: true

2025-05-04 14:05:47 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:47 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:48 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:48 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:50 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: RAISE
amount: 65

2025-05-04 14:05:51 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:51 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:52 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:52 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:53 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:53 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:54 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:54 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:55 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:55 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:55 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:55 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:56 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:56 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:57 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:58 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:58 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 14:05:59 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:05:59 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 14:06:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:06:00 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 14:06:00 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:06:00 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 14:06:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 14:06:01 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 14:06:02 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 14:06:04 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 14:06:34 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-04T14:06:34.681169-04:00"}"
>
2025-05-04 14:06:34 - INFO - Checking for leader...
2025-05-04 14:17:39 - INFO - Checking for leader...
2025-05-04 14:17:39 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 14:17:44 - INFO - Leader found: 127.0.0.1:50001
2025-05-04 14:17:44 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 14:19:47 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-05-04T14:19:47.2393-04:00"}"
>
2025-05-04 14:19:47 - INFO - Checking for leader...
2025-05-04 14:19:59 - INFO - Checking for leader...
2025-05-04 14:19:59 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 14:20:04 - INFO - Leader found: 127.0.0.1:50001
2025-05-04 14:20:04 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 14:20:55 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-04T14:20:55.919487-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-04 14:20:55 - INFO - Checking for leader...
2025-05-04 14:21:06 - INFO - Checking for leader...
2025-05-04 14:21:06 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 14:21:11 - INFO - Leader found: 127.0.0.1:50003
2025-05-04 14:21:11 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 14:22:08 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-05-04T14:22:08.235431-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-05-04 14:22:08 - INFO - Checking for leader...
